### ISSUE TITLE
Wrong parsing of tiles in tenhou format to tempai-core format

### ISSUE THREAD

**Issue by fumin** [dnovikoff/tenhou#2]
Hi Dmitry

In https://github.com/dnovikoff/tenhou/blob/master/client/xml_parser.go#L321 it seems that we simply cast the integer in tenhou's message to a tempai-core `tile.Instance`.
However, since the last few commits in tempai-core, the beginning offset for tiles and instances have been changed from 0 to 1.
In this case, the way we parse tenhou tiles and `hai` becomes wrong.

I am curious why do we change tempai-core's offset to 1, and make `tile.InstanceNull` be 0 instead of the previous -1? The previous approach seems to make it easier to interact with tenhou.

**Comment by dnovikoff** [comment]
Hi!
I'm working hard to prepare my private part of code to run with grpc/protobuf.
It seems to me, that having value of Zero for Null, and starting tiles numeration from one would be better. Also taking in consideration, the 'omitempty' for json/yaml and creating empty structs in code.

Thanks for the report - I'll look deeper in that code and will fix that issue.

**Comment by dnovikoff** [comment]
The code seems correct. Could you please provide the broken case (if any)
The code uses 	`t = util.InstanceFromTenhou(num)`
`func InstanceToTenhou(i tile.Instance) int {
	return int(i - tile.InstanceBegin)
}

func InstanceFromTenhou(i int) tile.Instance {
	return tile.Instance(i) + tile.InstanceBegin
}`

**Comment by fumin** [comment]
Ah, sorry, I apparently missed the latest commits, due to my browser tab pinned to commit `a93208d`. I confirm that the latest logic of `util.InstanceFromTenhou` is correct.

Also, thanks for pointing out that by having `InstanceNull` be 0, json automatically omits it.

Looking forward to your work on grpc! : )
